//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIT_PR_6_Cheb_Akhm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Cash> Cash { get; set; }
        public virtual DbSet<Deposits> Deposits { get; set; }
        public virtual DbSet<Expense_Categories> Expense_Categories { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<Income_Categories> Income_Categories { get; set; }
        public virtual DbSet<Incomes> Incomes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Transaction_History> Transaction_History { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
